[phases.setup]
aptPkgs = ["libpq-dev", "python3-dev", "build-essential"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "cd services/auth && uvicorn main:app --host 0.0.0.0 --port $PORT"
